[workspace]
members = ["crates/cargo-textus", "crates/textus-core", "crates/textus", "examples/demo"]
default-members = ["crates/cargo-textus", "crates/textus", "crates/textus-core"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[workspace.dependencies]
textus-core = { path = "crates/textus-core", version = "0.1.0" }
syn = "2"
quote = "1"
