//! 고정 버전 브라우저 자산을 바이너리에 포함해 설치 후 네트워크 없이 배치한다.
//! scripts/render-assets/vendor.py에서 생성한다.

/// 문서 루트 아래에 복사할 상대 경로와 원본 바이트. 폰트 상대 경로도 유지한다.
pub const FILES: &[(&str, &[u8])] = &[
    (
        "KATEX-LICENSE",
        include_bytes!("../assets/render/KATEX-LICENSE"),
    ),
    (
        "MERMAID-LICENSE",
        include_bytes!("../assets/render/MERMAID-LICENSE"),
    ),
    (
        "auto-render.js",
        include_bytes!("../assets/render/auto-render.js"),
    ),
    (
        "fonts/KaTeX_AMS-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_AMS-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_AMS-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_AMS-Regular.woff"),
    ),
    (
        "fonts/KaTeX_AMS-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_AMS-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Caligraphic-Bold.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Caligraphic-Bold.ttf"),
    ),
    (
        "fonts/KaTeX_Caligraphic-Bold.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Caligraphic-Bold.woff"),
    ),
    (
        "fonts/KaTeX_Caligraphic-Bold.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Caligraphic-Bold.woff2"),
    ),
    (
        "fonts/KaTeX_Caligraphic-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Caligraphic-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Caligraphic-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Caligraphic-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Caligraphic-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Caligraphic-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Fraktur-Bold.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Fraktur-Bold.ttf"),
    ),
    (
        "fonts/KaTeX_Fraktur-Bold.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Fraktur-Bold.woff"),
    ),
    (
        "fonts/KaTeX_Fraktur-Bold.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Fraktur-Bold.woff2"),
    ),
    (
        "fonts/KaTeX_Fraktur-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Fraktur-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Fraktur-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Fraktur-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Fraktur-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Fraktur-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Main-Bold.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Bold.ttf"),
    ),
    (
        "fonts/KaTeX_Main-Bold.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Bold.woff"),
    ),
    (
        "fonts/KaTeX_Main-Bold.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Bold.woff2"),
    ),
    (
        "fonts/KaTeX_Main-BoldItalic.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Main-BoldItalic.ttf"),
    ),
    (
        "fonts/KaTeX_Main-BoldItalic.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Main-BoldItalic.woff"),
    ),
    (
        "fonts/KaTeX_Main-BoldItalic.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Main-BoldItalic.woff2"),
    ),
    (
        "fonts/KaTeX_Main-Italic.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Italic.ttf"),
    ),
    (
        "fonts/KaTeX_Main-Italic.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Italic.woff"),
    ),
    (
        "fonts/KaTeX_Main-Italic.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Italic.woff2"),
    ),
    (
        "fonts/KaTeX_Main-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Main-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Main-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Main-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Math-BoldItalic.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Math-BoldItalic.ttf"),
    ),
    (
        "fonts/KaTeX_Math-BoldItalic.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Math-BoldItalic.woff"),
    ),
    (
        "fonts/KaTeX_Math-BoldItalic.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Math-BoldItalic.woff2"),
    ),
    (
        "fonts/KaTeX_Math-Italic.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Math-Italic.ttf"),
    ),
    (
        "fonts/KaTeX_Math-Italic.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Math-Italic.woff"),
    ),
    (
        "fonts/KaTeX_Math-Italic.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Math-Italic.woff2"),
    ),
    (
        "fonts/KaTeX_SansSerif-Bold.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Bold.ttf"),
    ),
    (
        "fonts/KaTeX_SansSerif-Bold.woff",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Bold.woff"),
    ),
    (
        "fonts/KaTeX_SansSerif-Bold.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Bold.woff2"),
    ),
    (
        "fonts/KaTeX_SansSerif-Italic.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Italic.ttf"),
    ),
    (
        "fonts/KaTeX_SansSerif-Italic.woff",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Italic.woff"),
    ),
    (
        "fonts/KaTeX_SansSerif-Italic.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Italic.woff2"),
    ),
    (
        "fonts/KaTeX_SansSerif-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_SansSerif-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Regular.woff"),
    ),
    (
        "fonts/KaTeX_SansSerif-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_SansSerif-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Script-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Script-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Script-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Script-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Script-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Script-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Size1-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Size1-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Size1-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Size1-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Size1-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Size1-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Size2-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Size2-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Size2-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Size2-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Size2-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Size2-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Size3-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Size3-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Size3-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Size3-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Size3-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Size3-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Size4-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Size4-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Size4-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Size4-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Size4-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Size4-Regular.woff2"),
    ),
    (
        "fonts/KaTeX_Typewriter-Regular.ttf",
        include_bytes!("../assets/render/fonts/KaTeX_Typewriter-Regular.ttf"),
    ),
    (
        "fonts/KaTeX_Typewriter-Regular.woff",
        include_bytes!("../assets/render/fonts/KaTeX_Typewriter-Regular.woff"),
    ),
    (
        "fonts/KaTeX_Typewriter-Regular.woff2",
        include_bytes!("../assets/render/fonts/KaTeX_Typewriter-Regular.woff2"),
    ),
    ("katex.css", include_bytes!("../assets/render/katex.css")),
    ("katex.js", include_bytes!("../assets/render/katex.js")),
    ("mermaid.js", include_bytes!("../assets/render/mermaid.js")),
];
